import {
  Bell,
  Blocks,
  Boxes,
  Building2,
  ChartColumnIncreasing,
  ClipboardList,
  Cog,
  DollarSign,
  FileClock,
  LayoutGrid,
  Package,
  Repeat2,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Store,
  TrendingUp,
  Users,
  Warehouse,
} from "lucide-react";
import {
  DashboardNotificationItem,
  DashboardWidgetDefinition,
  OnboardingStep,
  SellerDashboardModule,
  SellerFeatureFlags,
  SellerPlanTier,
} from "@/types/saas-dashboard";

export const SELLER_PLAN_ORDER: SellerPlanTier[] = ["FREE", "PRO", "BUSINESS"];

export const SELLER_FEATURES_BY_PLAN: Record<SellerPlanTier, SellerFeatureFlags> = {
  FREE: {
    dashboard: true,
    basicPOS: true,
    cashAndGcash: true,
    barcodeScan: true,
    products: true,
    orders: true,
    customers: true,
    settings: true,
    employees: false,
    inventory: false,
    reports: false,
    notifications: false,
    billing: false,
    advancedAnalytics: false,
    multiBranch: false,
    transfers: false,
    automation: false,
    auditLogs: false,
    forecasting: false,
    supplierAnalytics: false,
    branchComparison: false,
  },
  PRO: {
    dashboard: true,
    basicPOS: true,
    cashAndGcash: true,
    barcodeScan: true,
    products: true,
    orders: true,
    customers: true,
    settings: true,
    employees: true,
    inventory: true,
    reports: true,
    notifications: true,
    billing: true,
    advancedAnalytics: true,
    multiBranch: false,
    transfers: false,
    automation: false,
    auditLogs: false,
    forecasting: false,
    supplierAnalytics: true,
    branchComparison: false,
  },
  BUSINESS: {
    dashboard: true,
    basicPOS: true,
    cashAndGcash: true,
    barcodeScan: true,
    products: true,
    orders: true,
    customers: true,
    settings: true,
    employees: true,
    inventory: true,
    reports: true,
    notifications: true,
    billing: true,
    advancedAnalytics: true,
    multiBranch: true,
    transfers: true,
    automation: true,
    auditLogs: true,
    forecasting: true,
    supplierAnalytics: true,
    branchComparison: true,
  },
};

export const SELLER_MODULE_CATALOG: SellerDashboardModule[] = [
  {
    key: "dashboard",
    label: "Dashboard",
    href: "/seller/dashboard",
    icon: LayoutGrid,
    description: "At-a-glance operations and growth metrics.",
    requiredFeature: "dashboard",
  },
  {
    key: "multi-branch",
    label: "Multi-Branch",
    href: "/seller/branches",
    icon: Building2,
    description: "Branch switcher, comparisons, and branch KPIs.",
    requiredFeature: "multiBranch",
    upgradeMessage: "Available in BUSINESS plan",
  },
  {
    key: "pos",
    label: "POS",
    href: "/seller/pos",
    icon: Store,
    description: "Checkout, cashier operations, and slot usage.",
    requiredFeature: "basicPOS",
  },
  {
    key: "products",
    label: "Products",
    href: "/seller/products",
    icon: Package,
    description: "Catalog, pricing, and product lifecycle.",
    requiredFeature: "products",
  },
  {
    key: "orders",
    label: "Orders",
    href: "/seller/orders",
    icon: ShoppingCart,
    description: "Order queues and fulfillment performance.",
    requiredFeature: "orders",
  },
  {
    key: "customers",
    label: "Customers",
    href: "/seller/customers",
    icon: Users,
    description: "Customer profiles and retention insights.",
    requiredFeature: "customers",
  },
  {
    key: "employees",
    label: "Employees",
    href: "/seller/employees",
    icon: ShieldCheck,
    description: "Cashier accounts, roles, and activity logs.",
    requiredFeature: "employees",
    upgradeMessage: "Upgrade to PRO",
  },
  {
    key: "inventory",
    label: "Inventory",
    href: "/seller/inventory",
    icon: Warehouse,
    description: "Variants, categories, and low-stock automation.",
    requiredFeature: "inventory",
    upgradeMessage: "Upgrade to PRO",
  },
  {
    key: "transfers",
    label: "Transfers",
    href: "/seller/transfers",
    icon: Repeat2,
    description: "Cross-branch and warehouse stock movements.",
    requiredFeature: "transfers",
    upgradeMessage: "Available in BUSINESS plan",
  },
  {
    key: "analytics",
    label: "Analytics",
    href: "/seller/analytics",
    icon: ChartColumnIncreasing,
    description: "Branch comparison, forecasting, and trends.",
    requiredFeature: "advancedAnalytics",
    upgradeMessage: "Unlock with PRO",
  },
  {
    key: "reports",
    label: "Reports",
    href: "/seller/reports",
    icon: ClipboardList,
    description: "Exportable reports with advanced filters.",
    requiredFeature: "reports",
    upgradeMessage: "Unlock with PRO",
  },
  {
    key: "billing",
    label: "Billing",
    href: "/seller/pos",
    icon: DollarSign,
    description: "Subscription lifecycle, invoices, and upgrades.",
    requiredFeature: "billing",
    upgradeMessage: "Unlock with PRO",
  },
  {
    key: "automation",
    label: "Automation",
    href: "/seller/automation",
    icon: Sparkles,
    description: "Scheduled reports, smart alerts, and AI-ready workflows.",
    requiredFeature: "automation",
    upgradeMessage: "Available in BUSINESS plan",
  },
  {
    key: "audit-logs",
    label: "Audit Logs",
    href: "/seller/audit-logs",
    icon: FileClock,
    description: "Enterprise audit trail and policy controls.",
    requiredFeature: "auditLogs",
    upgradeMessage: "Available in BUSINESS plan",
  },
  {
    key: "settings",
    label: "Settings",
    href: "/seller/store-config",
    icon: Cog,
    description: "Store setup, preferences, and plan settings.",
    requiredFeature: "settings",
  },
];

export const SELLER_WIDGETS_BY_PLAN: Record<SellerPlanTier, DashboardWidgetDefinition[]> = {
  FREE: [
    {
      id: "today-sales",
      title: "Today Sales",
      metric: "PHP 12,450",
      delta: "+8.4% vs yesterday",
      tone: "success",
      featureKey: "dashboard",
    },
    {
      id: "total-orders",
      title: "Total Orders",
      metric: "87",
      delta: "+12 orders",
      tone: "neutral",
      featureKey: "orders",
    },
    {
      id: "product-count",
      title: "Product Count",
      metric: "214",
      delta: "14 recently updated",
      tone: "neutral",
      featureKey: "products",
    },
    {
      id: "low-stock",
      title: "Low Stock Alerts",
      metric: "9",
      delta: "3 critical items",
      tone: "warning",
      featureKey: "inventory",
    },
    {
      id: "recent-transactions",
      title: "Recent Transactions",
      metric: "31",
      delta: "Last 24 hours",
      tone: "neutral",
      featureKey: "orders",
    },
  ],
  PRO: [
    {
      id: "revenue-analytics",
      title: "Revenue Analytics",
      metric: "PHP 322,900",
      delta: "+14.1% month-over-month",
      tone: "success",
      featureKey: "advancedAnalytics",
    },
    {
      id: "monthly-sales",
      title: "Monthly Sales Graph",
      metric: "PHP 98,200",
      delta: "+5.8% this week",
      tone: "success",
      featureKey: "reports",
    },
    {
      id: "best-sellers",
      title: "Best Selling Products",
      metric: "12",
      delta: "Top category: beverages",
      tone: "neutral",
      featureKey: "products",
    },
    {
      id: "inventory-movement",
      title: "Inventory Movement",
      metric: "182",
      delta: "Skus moved today",
      tone: "neutral",
      featureKey: "inventory",
    },
    {
      id: "profit-estimates",
      title: "Profit Estimates",
      metric: "PHP 67,500",
      delta: "+9.9% margin",
      tone: "success",
      featureKey: "advancedAnalytics",
    },
    {
      id: "staff-activity",
      title: "Staff Activity",
      metric: "18",
      delta: "Cashier sessions active",
      tone: "neutral",
      featureKey: "employees",
    },
  ],
  BUSINESS: [
    {
      id: "executive-revenue",
      title: "Executive Revenue",
      metric: "PHP 1.48M",
      delta: "+18.2% quarter-over-quarter",
      tone: "success",
      featureKey: "advancedAnalytics",
    },
    {
      id: "branch-kpi",
      title: "Branch KPI Cards",
      metric: "6 branches",
      delta: "2 over target",
      tone: "neutral",
      featureKey: "branchComparison",
    },
    {
      id: "forecasting",
      title: "Forecasting",
      metric: "PHP 1.63M",
      delta: "Projected next month",
      tone: "success",
      featureKey: "forecasting",
    },
    {
      id: "ops-metrics",
      title: "Operational Metrics",
      metric: "97.4%",
      delta: "Fulfillment SLA",
      tone: "success",
      featureKey: "auditLogs",
    },
    {
      id: "transfers",
      title: "Transfers",
      metric: "42",
      delta: "Inter-branch transfers",
      tone: "neutral",
      featureKey: "transfers",
    },
    {
      id: "automation",
      title: "Automation Runs",
      metric: "26",
      delta: "Scheduled workflows today",
      tone: "neutral",
      featureKey: "automation",
    },
  ],
};

export const SELLER_SALES_SERIES = {
  FREE: [
    { label: "Mon", sales: 5200, orders: 22 },
    { label: "Tue", sales: 6700, orders: 28 },
    { label: "Wed", sales: 5900, orders: 25 },
    { label: "Thu", sales: 7200, orders: 31 },
    { label: "Fri", sales: 8450, orders: 35 },
    { label: "Sat", sales: 9100, orders: 42 },
    { label: "Sun", sales: 7800, orders: 30 },
  ],
  PRO: [
    { label: "W1", sales: 68200, profit: 21000, inventory: 182 },
    { label: "W2", sales: 74100, profit: 23600, inventory: 195 },
    { label: "W3", sales: 70200, profit: 22900, inventory: 188 },
    { label: "W4", sales: 82400, profit: 27000, inventory: 214 },
  ],
  BUSINESS: [
    { label: "North", revenue: 420000, margin: 31, transfers: 12 },
    { label: "South", revenue: 388000, margin: 28, transfers: 8 },
    { label: "East", revenue: 301000, margin: 26, transfers: 7 },
    { label: "West", revenue: 371000, margin: 29, transfers: 15 },
  ],
};

export const SELLER_NOTIFICATIONS: Record<SellerPlanTier, DashboardNotificationItem[]> = {
  FREE: [
    {
      id: "n1",
      title: "Low stock alert",
      body: "3 items are below reorder point.",
      level: "warning",
      timestamp: "2 mins ago",
    },
    {
      id: "n2",
      title: "Upgrade suggestion",
      body: "Unlock staff accounts with PRO to delegate cashier ops.",
      level: "info",
      timestamp: "1 hour ago",
    },
  ],
  PRO: [
    {
      id: "p1",
      title: "Monthly report ready",
      body: "April sales report is generated and ready for download.",
      level: "info",
      timestamp: "12 mins ago",
    },
    {
      id: "p2",
      title: "Subscription renewal",
      body: "Your PRO plan renews in 4 days.",
      level: "warning",
      timestamp: "2 hours ago",
    },
  ],
  BUSINESS: [
    {
      id: "b1",
      title: "Branch anomaly detected",
      body: "South branch saw 17% drop in evening conversion.",
      level: "critical",
      timestamp: "5 mins ago",
    },
    {
      id: "b2",
      title: "Automation complete",
      body: "Daily transfer balancing finished across all branches.",
      level: "info",
      timestamp: "31 mins ago",
    },
  ],
};

export const SELLER_ONBOARDING_STEPS: Record<SellerPlanTier, OnboardingStep[]> = {
  FREE: [
    {
      id: "f1",
      label: "Complete store profile",
      description: "Add logo, address, and business hours.",
      featureKey: "settings",
    },
    {
      id: "f2",
      label: "Add at least 20 products",
      description: "Build your starter catalog for cashier flow.",
      featureKey: "products",
    },
    {
      id: "f3",
      label: "Enable barcode scanning",
      description: "Speed up checkout on your POS device.",
      featureKey: "barcodeScan",
    },
  ],
  PRO: [
    {
      id: "p1",
      label: "Invite cashiers",
      description: "Create role-based staff accounts.",
      featureKey: "employees",
    },
    {
      id: "p2",
      label: "Set low-stock automation",
      description: "Get proactive alerts before stockouts.",
      featureKey: "inventory",
    },
    {
      id: "p3",
      label: "Schedule weekly reports",
      description: "Receive PDF reports every Monday.",
      featureKey: "reports",
    },
  ],
  BUSINESS: [
    {
      id: "b1",
      label: "Connect all branches",
      description: "Configure branch switcher and baseline KPIs.",
      featureKey: "multiBranch",
    },
    {
      id: "b2",
      label: "Enable transfer workflows",
      description: "Route stock automatically between branches.",
      featureKey: "transfers",
    },
    {
      id: "b3",
      label: "Turn on executive forecast",
      description: "Use trend models for planning and purchasing.",
      featureKey: "forecasting",
    },
  ],
};

export const SELLER_QUICK_ACTIONS = [
  {
    id: "qa-1",
    label: "Create Product",
    icon: Boxes,
    href: "/seller/products",
  },
  {
    id: "qa-2",
    label: "Open POS",
    icon: Store,
    href: "/seller/pos",
  },
  {
    id: "qa-3",
    label: "Review Billing",
    icon: DollarSign,
    href: "/seller/pos",
  },
  {
    id: "qa-4",
    label: "Run Report",
    icon: TrendingUp,
    href: "/seller/reports",
  },
  {
    id: "qa-5",
    label: "Automate Flow",
    icon: Blocks,
    href: "/seller/automation",
  },
  {
    id: "qa-6",
    label: "Open Alerts",
    icon: Bell,
    href: "/seller/notifications",
  },
];

export const getPlanUpgradeMessage = (plan: SellerPlanTier) => {
  if (plan === "FREE") {
    return "Upgrade to PRO to unlock staff accounts, reports, and advanced analytics.";
  }

  if (plan === "PRO") {
    return "Upgrade to BUSINESS for branch operations, transfers, and executive automation.";
  }

  return "BUSINESS plan active. Enterprise modules are fully unlocked.";
};

export const isFeatureEnabled = (plan: SellerPlanTier, feature: keyof SellerFeatureFlags) =>
  Boolean(SELLER_FEATURES_BY_PLAN[plan][feature]);
